# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20180603_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
