# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-16 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import listings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[listings.validators.validate_category]),
        ),
    ]
